name: Install Terraform
on:
  workflow_dispatch

jobs:
  install-terraform:
    runs-on: [self-hosted, runner-1]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Unzip (Ubuntu/Debian)
        run: sudo apt-get update && sudo apt-get install -y unzip

      - name: Install Node.js (Required for Terraform GitHub Action)
        uses: actions/setup-node@v4
        with:
          node-version: 18  # Use latest stable version

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.0  # Change to the version you need

      - name: Verify Terraform Installation
        run: terraform version
