name: Install Terraform
on:
  workflow_dispatch

jobs:
  install-terraform:
    runs-on: [self-hosted, runner-1]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.11.0  # Change to the version you need

      - name: Verify Terraform Installation
        run: terraform version